# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/xpy/xport

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/xpy/xport

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xpy/xport/CMakeFiles /home/xpy/xport/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xpy/xport/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named xport

# Build rule for target.
xport: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xport
.PHONY : xport

# fast build rule for target.
xport/fast:
	$(MAKE) -f src/CMakeFiles/xport.dir/build.make src/CMakeFiles/xport.dir/build
.PHONY : xport/fast

#=============================================================================
# Target rules for targets named xporttest

# Build rule for target.
xporttest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xporttest
.PHONY : xporttest

# fast build rule for target.
xporttest/fast:
	$(MAKE) -f test/CMakeFiles/xporttest.dir/build.make test/CMakeFiles/xporttest.dir/build
.PHONY : xporttest/fast

#=============================================================================
# Target rules for targets named mix_demo

# Build rule for target.
mix_demo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mix_demo
.PHONY : mix_demo

# fast build rule for target.
mix_demo/fast:
	$(MAKE) -f example/CMakeFiles/mix_demo.dir/build.make example/CMakeFiles/mix_demo.dir/build
.PHONY : mix_demo/fast

#=============================================================================
# Target rules for targets named m3u8_demo

# Build rule for target.
m3u8_demo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 m3u8_demo
.PHONY : m3u8_demo

# fast build rule for target.
m3u8_demo/fast:
	$(MAKE) -f example/CMakeFiles/m3u8_demo.dir/build.make example/CMakeFiles/m3u8_demo.dir/build
.PHONY : m3u8_demo/fast

#=============================================================================
# Target rules for targets named decrypt_demo

# Build rule for target.
decrypt_demo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 decrypt_demo
.PHONY : decrypt_demo

# fast build rule for target.
decrypt_demo/fast:
	$(MAKE) -f example/CMakeFiles/decrypt_demo.dir/build.make example/CMakeFiles/decrypt_demo.dir/build
.PHONY : decrypt_demo/fast

#=============================================================================
# Target rules for targets named simple_demo

# Build rule for target.
simple_demo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simple_demo
.PHONY : simple_demo

# fast build rule for target.
simple_demo/fast:
	$(MAKE) -f example/CMakeFiles/simple_demo.dir/build.make example/CMakeFiles/simple_demo.dir/build
.PHONY : simple_demo/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... xport"
	@echo "... xporttest"
	@echo "... mix_demo"
	@echo "... m3u8_demo"
	@echo "... decrypt_demo"
	@echo "... simple_demo"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

